name: Auto Assign PR Creator

on:
  pull_request:
    types: [opened]

permissions:
  pull-requests: write

jobs:
  auto-assign:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request;
            const repository = context.payload.repository;
            try {
              await github.rest.issues.addAssignees({
                owner: repository.owner.login,
                repo: repository.name,
                issue_number: pr.number,
                assignees: [pr.user.login]
              });
              console.log(`Successfully assigned ${pr.user.login} to PR #${pr.number}`);
            } catch (error) {
              console.error('Failed to assign PR creator:', error);
              core.setFailed(error.message);
            }
