name: Chromatic

on:
  pull_request:
    types: [opened, ready_for_review, synchronize]
    branches:
      - main
    paths:
      - '**/*.stories.@(js|jsx|ts|tsx)'
  push:
    branches:
      - main
    paths:
      - '**/*.stories.@(js|jsx|ts|tsx)'
  
jobs:
  chromatic:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          cache: pnpm
          node-version-file: .nvmrc
      - name: Install dependencies
        run: pnpm install
      - name: Run Chromatic
        id: chromatic
        uses: chromaui/action@latest
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
      - name: comment PR
        uses: thollander/actions-comment-pull-request@v1
        if: ${{ github.event_name == 'pull_request' }}
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_BOT_TOKEN }}
        with:
          message: "💅 The Storybook has been updated! Click [here](${{ steps.chromatic.outputs.storybookUrl }}) to check it out."
