name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          cache: pnpm
          node-version-file: .nvmrc
          registry-url: https://npm.pkg.github.com
          scope: "@sipe-team"
      - name: Install dependencies
        run: pnpm install
      - name: Create Release Pull Request or Publish to Github Package Registry
        id: changesets
        uses: changesets/action@v1
        with:
          version: pnpm changeset version
          publish: pnpm changeset publish
          commit: "chore(release): Version Packages"
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_BOT_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.RELEASE_BOT_TOKEN }}
